"""Add verify_code, status, verify_try, reset_code, reset_try, created_at, and updated_at columns to User

Revision ID: 7a8e7f16f2e8
Revises: 
Create Date: 2024-11-10 00:49:53.447269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8e7f16f2e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verify_code', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('verify_try', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reset_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reset_try', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('reset_try')
        batch_op.drop_column('reset_code')
        batch_op.drop_column('verify_try')
        batch_op.drop_column('status')
        batch_op.drop_column('verify_code')

    # ### end Alembic commands ###
